# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.66.2"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "2350cdb9-7b2f-4eae-94a3-5615ca09b343"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # cocoapods
    # carthage
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  # lane :increment_build_number do
  #   increment_build_number(build_number: ENV['CI_BUILD_ID'])
  # end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    increment_build_number

    # build your iOS app
    gym(
      # scheme: "YourScheme",
      # export_method: "app-store"
    )

    # upload to Testflight
    pilot()

    # # match(type: "appstore") # more information: https://codesigning.guide
    # gym(scheme: "input") # Build your app - more options available
    # pilot

    # # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  # desc "Deploy a new version to the App Store"
  # lane :release do
  #   # match(type: "appstore")
  #   # snapshot
  #   # gym(scheme: "input") # Build your app - more options available
  #   # deliver(force: true)
  #   # frameit
  # end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://docs.fastlane.tools/advanced/#control-configuration-by-lane-and-by-platform
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics


lane :icon do
  appicon(appicon_image_file: 'fastlane/app_icon.png',
  appicon_devices: [:ipad, :iphone, :ios_marketing])
end
